
export default async () => {
    try {

    }
    catch(err) {
        throw(err);
    }
}